services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mp_pro
      POSTGRES_PASSWORD: mp_pro
      POSTGRES_DB: mp_pro
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
